### ISSUE TITLE
Handle missing values 

### ISSUE THREAD

**Issue by xiw588** [Genentech/midasHLA#21] opened 2023-03-23 14:41 UTC
Hi I have a question about how this package handle missing values in HLA types. For example, a sample may have only one HLA classI A allele available, and no DRA alleles at all. Should I replace all the blanks with NA or so to run through the functions, such as hlaToVariable()? 

Thanks a lot!

**Comment by xiw588** [comment] 2023-03-24 04:13
Hi I figured this out but came around another issue when applying hlaCallsGranthamDistance() to the dataframe that I used for hlaToVariable(). I received the following error message.  Do you have any idea of what is the wrong here? Thanks
" Error in alignment[allele1, ] : invalid subscript type 'list' "

**Comment by mcjmigdal** [comment] 2023-03-24 07:26
Unfortunately, I do not recognize this error message. Could you provide some data so that I could reproduce this error?

**Comment by mcjmigdal** [comment] 2023-03-28 15:38
@xiw588 while I am not familiar with the tool you have provided, my guess would be that the differences may steam from different choice of peptide region used in the calculation. For more details I am referring you to `midasHLA` documentation on `hlaCallsGranthamDistance`:

```
...
Grantham distance is calculated only for class I HLA alleles. First
exons forming the variable region in the peptide binding groove are selected.
Here we provide option to choose either "binding_groove" - exon 2 and
3 (positions 1-182 in IMGT/HLA alignments, however here we take 2-182 as many
1st positions are missing), "B_pocket" -  residues 7, 9, 24, 25, 34,
45, 63, 66, 67, 70, 99 and "F_pocket" - residues 77, 80, 81, 84, 95,
116, 123, 143, 146, 147. Then all the alleles containing gaps, stop codons or
indels are discarded. Finally distance is calculated for each pair.
...
```

But that is all guessing, unless you provide a concrete example that I can reproduce on my side it is impossible for me to tell what is happening.

**Comment by xiw588** [comment] 2023-03-28 20:09
Hi Thank you so much for your response. This could be a possibility and I am wondering if the normalization process play a role too.  For example A0101 and A2402, I got 10.60773 from your algorithm and 0.138121547 from the other.

**Comment by mcjmigdal** [comment] 2023-03-28 21:36
Ok, so eventually I've tried `granthamdist` pearl scripts you were referencing and i got the same result in both tools:

1. `granthamdist` 
[inp.txt](https://github.com/Genentech/midasHLA/files/11094311/inp.txt)
```
» perl CalculateIndividualDivergence.pl -f HLA_ClassI_CWDonly.fas -i inp.txt

***********
Command line: -f HLA_ClassI_CWDonly.fas -i inp.txt
Genotype file: inp.txt
Fasta file: HLA_ClassI_CWDonly.fas
Distance matrix used: AAdistMatrix_Grantham.cnv
***********

Calculating distances...

Calculations finished (1 genotypes processed) and output file created:
        inp.txt.IndividualDivergence.txt

» cat inp.txt.IndividualDivergence.txt
ID      AlleleNumber    Divergence_Average      Divergence_Sum  AlleleList
ID2     2       10.6077348066298        10.6077348066298        A2402   A0101
```

2. midasHLA
```
> df <- data.frame(ID = c("S1", "S2"), A_1 = c("A*01:01", "A*24:02"), A_2 = c("A*24:02", "A*01:01"))
> hlaCallsGranthamDistance(df, "A")
   ID        A
1 S1 10.60773
2 S2 10.60773
```

I am closing this issue since it diverged from the original topic of handling missing values.

**Closed by mcjmigdal** 2023-03-28 21:36 UTC
